version: '3.9'

services:
  client:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: portfolio-client
    volumes:
      - ./nginx/templates/:/etc/nginx/templates/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    env_file:
      - ./.env.local
    ports:
      - "8060:80"
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge

